#!/bin/sh
# The next line is executed by /bin/sh, but not Tcl \
exec tclsh $0 ${1+"$@"}

###############################################################################
##
## BSD 3-Clause License
##
## Copyright (c) 2019, Parallax Software, Inc.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are met:
##
## * Redistributions of source code must retain the above copyright notice, this
##   list of conditions and the following disclaimer.
##
## * Redistributions in binary form must reproduce the above copyright notice,
##   this list of conditions and the following disclaimer in the documentation
##   and#or other materials provided with the distribution.
##
## * Neither the name of the copyright holder nor the names of its
##   contributors may be used to endorse or promote products derived from
##   this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
## AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
## ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
## LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
## CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
## SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
## INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
## CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
## POSSIBILITY OF SUCH DAMAGE.
##
###############################################################################

# Usage: regression [-help] [-timing_gradpass_top_n N] [-timing_gradpass_proj_weight W]
#                   [-timing_gradpass_end_to_end_weight W] [-timing_gradpass_slack_sharpness S]
#                   [-timing_gradpass_slack_offset O] [test1 [test2...]]
# Where test1 is all or the name of a tcl script in /test
# Wildcard matching with '*' and '?' in test names is supported.
#
# Timing gradient pass parameters (from commit 883c9767):
#   -timing_gradpass_top_n N            : Number of top timing paths to consider (default: 10)
#   -timing_gradpass_proj_weight W      : Projection weight for timing gradient (default: 1.0)
#   -timing_gradpass_end_to_end_weight W: End-to-end weight for timing gradient (default: 1.0)
#   -timing_gradpass_slack_sharpness S : Slack sharpness factor (default: 1.0)
#   -timing_gradpass_slack_offset O     : Slack offset value (default: 0.0)

# Directory containing tests.
set test_dir [file dirname [file normalize [info script]]]
set openroad_dir [file dirname [file dirname [file dirname $test_dir]]]

# Default timing gradient pass parameters (matching PlaceOptions defaults)
set ::gpl_timing_gradpass_top_n 10
set ::gpl_timing_gradpass_proj_weight 1.0
set ::gpl_timing_gradpass_end_to_end_weight 1.0
set ::gpl_timing_gradpass_slack_sharpness 1.0
set ::gpl_timing_gradpass_slack_offset 0.0

# Parse timing gradient pass arguments from command line
proc parse_timing_gradpass_args { cmd_argv } {
  global ::gpl_timing_gradpass_top_n
  global ::gpl_timing_gradpass_proj_weight
  global ::gpl_timing_gradpass_end_to_end_weight
  global ::gpl_timing_gradpass_slack_sharpness
  global ::gpl_timing_gradpass_slack_offset
  
  set remaining {}
  set i 0
  while { $i < [llength $cmd_argv] } {
    set arg [lindex $cmd_argv $i]
    switch -exact -- $arg {
      "-timing_gradpass_top_n" {
        incr i
        if { $i < [llength $cmd_argv] } {
          set ::gpl_timing_gradpass_top_n [lindex $cmd_argv $i]
        } else {
          puts "Error: -timing_gradpass_top_n requires a value"
          exit 1
        }
      }
      "-timing_gradpass_proj_weight" {
        incr i
        if { $i < [llength $cmd_argv] } {
          set ::gpl_timing_gradpass_proj_weight [lindex $cmd_argv $i]
        } else {
          puts "Error: -timing_gradpass_proj_weight requires a value"
          exit 1
        }
      }
      "-timing_gradpass_end_to_end_weight" {
        incr i
        if { $i < [llength $cmd_argv] } {
          set ::gpl_timing_gradpass_end_to_end_weight [lindex $cmd_argv $i]
        } else {
          puts "Error: -timing_gradpass_end_to_end_weight requires a value"
          exit 1
        }
      }
      "-timing_gradpass_slack_sharpness" {
        incr i
        if { $i < [llength $cmd_argv] } {
          set ::gpl_timing_gradpass_slack_sharpness [lindex $cmd_argv $i]
        } else {
          puts "Error: -timing_gradpass_slack_sharpness requires a value"
          exit 1
        }
      }
      "-timing_gradpass_slack_offset" {
        incr i
        if { $i < [llength $cmd_argv] } {
          set ::gpl_timing_gradpass_slack_offset [lindex $cmd_argv $i]
        } else {
          puts "Error: -timing_gradpass_slack_offset requires a value"
          exit 1
        }
      }
      "-help" -
      "-h" {
        puts {Usage: regression-large [-help] [-timing_gradpass_top_n N]}
        puts {                  [-timing_gradpass_proj_weight W]}
        puts {                  [-timing_gradpass_end_to_end_weight W]}
        puts {                  [-timing_gradpass_slack_sharpness S]}
        puts {                  [-timing_gradpass_slack_offset O]}
        puts {                  [test1 [test2...]]}
        puts {}
        puts {Timing gradient pass parameters:}
        puts {  -timing_gradpass_top_n N            : Number of top timing paths (default: 10)}
        puts {  -timing_gradpass_proj_weight W      : Projection weight (default: 1.0)}
        puts {  -timing_gradpass_end_to_end_weight W: End-to-end weight (default: 1.0)}
        puts {  -timing_gradpass_slack_sharpness S  : Slack sharpness (default: 1.0)}
        puts {  -timing_gradpass_slack_offset O     : Slack offset (default: 0.0)}
        puts {}
        puts {Tests are: all, fast, med, slow, or a test group or test name}
        exit 0
      }
      default {
        lappend remaining $arg
      }
    }
    incr i
  }
  return $remaining
}

# Get timing gradient pass arguments for global_placement command
proc get_timing_gradpass_args { } {
  global ::gpl_timing_gradpass_top_n
  global ::gpl_timing_gradpass_proj_weight
  global ::gpl_timing_gradpass_end_to_end_weight
  global ::gpl_timing_gradpass_slack_sharpness
  global ::gpl_timing_gradpass_slack_offset
  
  return [list \
    -timing_gradpass_top_n $::gpl_timing_gradpass_top_n \
    -timing_gradpass_proj_weight $::gpl_timing_gradpass_proj_weight \
    -timing_gradpass_end_to_end_weight $::gpl_timing_gradpass_end_to_end_weight \
    -timing_gradpass_slack_sharpness $::gpl_timing_gradpass_slack_sharpness \
    -timing_gradpass_slack_offset $::gpl_timing_gradpass_slack_offset]
}

source [file join $openroad_dir "test" "regression.tcl"]
source [file join $test_dir "regression_tests_large.tcl"]

# Parse timing gradient pass arguments and pass remaining to regression
set argv [parse_timing_gradpass_args $argv]

# Print timing gradpass parameters before running tests
puts "Timing gradpass parameters:"
puts "  -timing_gradpass_top_n = $::gpl_timing_gradpass_top_n"
puts "  -timing_gradpass_proj_weight = $::gpl_timing_gradpass_proj_weight"
puts "  -timing_gradpass_end_to_end_weight = $::gpl_timing_gradpass_end_to_end_weight"
puts "  -timing_gradpass_slack_sharpness = $::gpl_timing_gradpass_slack_sharpness"
puts "  -timing_gradpass_slack_offset = $::gpl_timing_gradpass_slack_offset"
puts ""

regression_main

# Local Variables:
# mode:tcl
# End:
